# Site
repository: ciehanski/ciehanski.com
favicon: assets/images/favicon.ico

# Personal info
name: Ryan Ciehanski
title: Software Engineer
email: ryan@ciehanski.com
website: www.github.com/ciehanski

# Social links
twitter_username: mrciehanski
github_username:  ciehanski
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: mrciehanski
linkedin_username: ciehanski
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
additional_links:
- title: My Blog
  icon: fab fa-wordpress
  url: https://blog.ciehanski.com
- title: Email Me
  icon: fas fa-envelope
  url: mailto:ryan@ciehanski.com?Subject=Hey%20Ryan!

# About Section
about_title: About Me
about_profile_image: assets/images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Congrats! You found me. I've been tinkering with computers since I was 10 years old. I built my first computer when I was 11 (thank you Dad) and the rest is history. I am always learning and adding something new to my toolbox.  
    
  Don't hesitate to reach out.  
  <mark>~Ryan</mark>

# Projects Section
projects_title: My Projects

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering, IT security, & online privacy, some of my other interests & hobbies include:
   - Browsing Reddit
   - Watches
   - Entrepreneurship
   - Watching Leonardo DiCaprio Movies
   - Contributing To Wikipedia

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
#  - jekyll-sitemap
