# Site
repository: ciehanski/ciehanski.com
favicon: images/favicon.ico

# Personal info
name: Ryan Ciehanski
title: Passionate Software Developer & Entrepreneur
email: ryan@ciehanski.com
website: www.github.com/ciehanski

# Social links
twitter_username: mrciehanski
github_username:  ciehanski
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mrciehanski
linkedin_username: ciehanski
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Congrats! You found me. I've been tinkering with computers since I was 10 years old. I built my first computer when I was 11 (thank you Dad) and the rest is history. I am deeply intrigued by computer infrastructures and how they're managed, how networks are designed, and how data flows from one system to the next. I am always learning and adding something new to my toolbox which makes Information Technology such an exciting field for me. Never a dull day!

Don't hesitate to reach out.
<mark>~Ryan</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
